/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs;

import clases.GrafoDefinitivo;
import clases.Lista;
import clases.Txt;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class AñadirUsuario extends javax.swing.JFrame {

    /**
     * @return the relaciones
     */
    public javax.swing.JTextField getRelaciones() {
        return relaciones;
    }
    private GrafoDefinitivo g;
    private String path;
    /**
     * Creates new form AñadirUsuario
     */
    public AñadirUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TItuloAñadir = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        relaciones = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        añadir = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        confirmacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FondoAñadir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 72, -1, -1));

        TItuloAñadir.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TItuloAñadir.setForeground(new java.awt.Color(255, 255, 255));
        TItuloAñadir.setText("Añadir Usuario");
        getContentPane().add(TItuloAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 390, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 390, 30));
        getContentPane().add(relaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 390, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Añadir Relaciones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        añadir.setText("Añadir");
        añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirActionPerformed(evt);
            }
        });
        getContentPane().add(añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        confirmacion.setForeground(new java.awt.Color(255, 0, 0));
        confirmacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 230, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Formato: Usuario1, Usuario2, Usuario3, ...");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 280, -1));

        FondoAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIs/FondoAñadir.jpeg"))); // NOI18N
        getContentPane().add(FondoAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirActionPerformed
       Txt t2 = new Txt();
        if (name.getText().equalsIgnoreCase("") || t2.leer_txt(getPath()).contains(name.getText())){
            if ( name.getText().equalsIgnoreCase("")){
           JOptionPane.showMessageDialog(null, "Por favor ingrese un nombbre valido");
           }
           if (t2.leer_txt(getPath()).contains(name.getText())){
               JOptionPane.showMessageDialog(null, "El usuario ya existe");
               name.setText("");
               confirmacion.setText("Solo puede añadir usuarios nuevos");
           }
        }else{
        String nombre=name.getText();
        String relacion = getRelaciones().getText();
        String[] splits = relacion.split(",");
        Lista relations = new Lista();
        if (getRelaciones().getText()!=""){
            for (int i=0;i<splits.length;i++){
                if (t2.leer_txt(getPath()).contains(splits[i].replace(" ",""))){
                relations.insertFinale(splits[i].replace(" ",""));
                }else{
                    JOptionPane.showMessageDialog(null, "Algunos usuarios ingresados en las relaciones no estan registrados"+"\n"+nombre+" "+"ha sido registrado con las relaiones a ususarios existentes");
                }
            }
        }
       setG(getG().insertUsuarioGrafo(nombre, relations));
       Txt t = new Txt();
       t.modificarTxt(getPath(), t.modifiarStringAdd(t.leer_txt(getPath()), nombre, relations));
       setG(getG().completarGrafo());
       confirmacion.setText("El usuario fue añadido exitosamente");
       }
    }//GEN-LAST:event_añadirActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        ModificarGrafo v = new ModificarGrafo();
        v.setG(getG());
        v.setPath(getPath());
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoAñadir;
    private javax.swing.JLabel TItuloAñadir;
    private javax.swing.JButton añadir;
    private javax.swing.JTextField confirmacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField relaciones;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the g
     */
    public GrafoDefinitivo getG() {
        return g;
    }

    /**
     * @param g the g to set
     */
    public void setG(GrafoDefinitivo g) {
        this.g = g;
    }

    /**
     * @return the path
     */
    public String getPath() {
        return path;
    }

    /**
     * @param path the path to set
     */
    public void setPath(String path) {
        this.path = path;
    }
}
