/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIs;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ACER
 */
public class InterfazGeneral extends javax.swing.JFrame {

    /**
     * Creates new form interfazisolda
     */
    public InterfazGeneral() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloInterfazGeneral = new javax.swing.JLabel();
        CargarArchivoBut = new javax.swing.JButton();
        ArchivoPrevioBut = new javax.swing.JButton();
        FondoInterfazGeneral = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        TituloInterfazGeneral.setBackground(new java.awt.Color(255, 255, 255));
        TituloInterfazGeneral.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloInterfazGeneral.setForeground(new java.awt.Color(255, 255, 255));
        TituloInterfazGeneral.setText("Proyecto1 Análisis de redes sociales");
        getContentPane().add(TituloInterfazGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 830, 110));

        CargarArchivoBut.setBackground(new java.awt.Color(0, 0, 0));
        CargarArchivoBut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CargarArchivoBut.setForeground(new java.awt.Color(255, 255, 255));
        CargarArchivoBut.setText("Cargar Archivo");
        CargarArchivoBut.setBorderPainted(false);
        CargarArchivoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoButActionPerformed(evt);
            }
        });
        getContentPane().add(CargarArchivoBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 260, 110));

        ArchivoPrevioBut.setBackground(new java.awt.Color(0, 0, 0));
        ArchivoPrevioBut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ArchivoPrevioBut.setForeground(new java.awt.Color(255, 255, 255));
        ArchivoPrevioBut.setText("Usar archivo previo");
        ArchivoPrevioBut.setBorderPainted(false);
        ArchivoPrevioBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoPrevioButActionPerformed(evt);
            }
        });
        getContentPane().add(ArchivoPrevioBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 260, 110));

        FondoInterfazGeneral.setBackground(new java.awt.Color(51, 255, 51));
        FondoInterfazGeneral.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(FondoInterfazGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArchivoPrevioButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoPrevioButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArchivoPrevioButActionPerformed

    private void CargarArchivoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoButActionPerformed

        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("TXT","txt");
        jFileChooser.setFileFilter(filtrado);
        
        int respuesta = jFileChooser.showOpenDialog(this);
        
        if (respuesta==JFileChooser.APPROVE_OPTION) {
            String Ruta = jFileChooser.getSelectedFile().getPath();
            JOptionPane.showMessageDialog(null, "El archivo se leyó ");
            this.setVisible(false);
            CargarArchivo ventanacargar = new CargarArchivo();
            ventanacargar.setVisible(true);
            
        }
    }//GEN-LAST:event_CargarArchivoButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArchivoPrevioBut;
    private javax.swing.JButton CargarArchivoBut;
    private javax.swing.JLabel FondoInterfazGeneral;
    private javax.swing.JLabel TituloInterfazGeneral;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
